# Generated by Django 5.2.6 on 2025-10-05 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('prioridad_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=12)),
                ('nivel', models.IntegerField()),
                ('sla_horas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('dv', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('K', 'K')], max_length=1)),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('contrasenia_hash', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_PROGRESO', 'En Progreso'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado'), ('RECHAZADO', 'Rechazado')], default='ABIERTO', max_length=20)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('cerrado_en', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.categoria')),
                ('prioridad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.prioridad')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_creados', to='tickets.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionTicket',
            fields=[
                ('asignacion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('comentarios', models.CharField(max_length=255)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
                ('usuario_asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='tickets.usuario')),
            ],
        ),
    ]
