# Generated by Django 5.2.6 on 2025-10-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prioridad',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='prioridad',
            name='nombre',
        ),
        migrations.AddField(
            model_name='prioridad',
            name='Tipo_Nivel',
            field=models.CharField(choices=[('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('BAJO', 'Bajo')], default='MEDIO', max_length=12),
        ),
    ]
