# Generated by Django 5.2.6 on 2025-10-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_asignacionticket_fecha_asignacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionticket',
            name='fecha_asignacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cerrado_en',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
