# Generated by Django 5.2.6 on 2025-10-26 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_asignacionticket_fecha_asignacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('notificacion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=255)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_ticket', to='tickets.ticket')),
                ('usuario_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='tickets.usuario')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
