# Generated by Django 5.2.6 on 2025-11-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_asignacionticket_fecha_asignacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionticket',
            name='comentarios',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cerrado_en',
            field=models.DateField(blank=True, null=True),
        ),
    ]
