# Generated by Django 5.2.6 on 2025-11-25 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_asignacionticket_comentarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.categoria'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='prioridad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.prioridad'),
        ),
    ]
