# Generated by Django 5.2.6 on 2025-11-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_ticket_categoria_alter_ticket_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fijado',
            field=models.BooleanField(default=False),
        ),
    ]
